import = [
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

# [env]
# WINIT_X11_SCALE_FACTOR = "1.5"
#
[font]
size = 21

[window]
opacity = 0.9
decorations = "Buttonless"

[font.normal]
family="UbuntuMono Nerd Font"

[window.padding]
x = 5
y = 8

